### ISSUE TITLE
Your default, ip6-privacy=0 leaks Ipv6 mac addresses all over the web

### ISSUE THREAD

**Issue by ravenise** [strobilomyces/nordvpn-import-ikev2#1]
ip6-privacy=2 fixes this

Source: https://superuser.com/questions/243669/how-to-avoid-exposing-my-mac-address-when-using-ipv6

**Quote:** On my Macs, each IPv6 address includes the MAC address of a specific computer (not of my router). Sites such as ipv6-test.com not only show it, but even tell me it belongs to an Apple computer.

This feels like a super cookie, and might apply to other operating systems as well. How can I avoid my MAC addresses from being exposed?

**answer:**
This is what IPv6 Privacy Addressing is for. When enabled, the system will generate a temporary address with a random suffix in addition to the EUI-64-based address.

Windows (starting with XP SP2) – enabled by default in XP, Vista, 7:

netsh interface ipv6 set privacy state=enabled
Note that Windows no longer uses the MAC address for IPv6 anyway – it has started using a scheme similar to RFC 7217, with unique per-network addresses.

Linux with NetworkManager:

Recent versions of NetworkManager handle RA on their own, although the two values below have identical meanings to sysctl (2 = prefer privacy address, 1 = prefer main address):

nmcli con modify <name> ipv6.ip6-privacy 2
Also, as of 1.2.0 a better mode became available, which changes the main address to no longer be MAC-based but instead unique for every network (RFC 7217):

nmcli con modify <name> ipv6.addr-gen-mode stable-privacy
(Note that privacy addressing is orthogonal to addr-gen-mode; it's possible to use both.)

Side note: As of 1.4.0, NM allows randomizing the MAC address itself, too. Set wifi.cloned-mac-address to stable to have a different MAC for every network (recommended), or random to randomize it for every connection (may cause problems).

In all cases, <name> must be the connection name, e.g. WiFi SSID or "Wired Connection 1". Use nmcli con to list all.

To make this the default for new connections, as of 1.2.0 you can change /etc/NetworkManager/NetworkManager.conf:

[connection]
ipv6.addr-gen-mode=stable-privacy
wifi.cloned-mac-address=stable
Linux with kernel RA:

To enable temporary addresses and make them preferred for outgoing connections:

sysctl net.ipv6.conf.all.use_tempaddr=2
sysctl net.ipv6.conf.default.use_tempaddr=2
To enable temporary address generation, but keep the old (Autoconf) address as preferred:

sysctl net.ipv6.conf.all.use_tempaddr=1
sysctl net.ipv6.conf.default.use_tempaddr=1
The all or default part can be replaced with a specific interface name; e.g. net.ipv6.conf.eth0.use_tempaddr.

(I used ip link set eth0 down && ip link set eth0 up to force an address assignment, but you can also run rdisc6 eth0 or just wait a few minutes for the next periodic Router Advertisement.)

Mac OS X – enabled by default since OS X 10.7 Lion:

sysctl -w net.inet6.ip6.use_tempaddr=1
Temporary addresses, if enabled, will be preferred.

FreeBSD:

sysctl net.inet6.ip6.use_tempaddr=1

sysctl net.inet6.ip6.prefer_tempaddr=1
NetBSD:

sysctl -w net.inet6.ip6.use_tempaddr=1
Temporary addresses preference? I have no idea. The autoconf address seems to be preferred.  ifconfig doesn't appear to list any address properties.

OpenBSD – support added in 5.2; enabled and preferred by default in 5.3.

ifconfig em0 autoconfprivacy
ifconfig shows "autoconfprivacy" next to temporary addresses.

Notes on configuration:

On Linux, OS X, and all BSDs, edit /etc/sysctl.conf to make the setting permanent.

On Windows, the changes will persist automatically.

(Append store=active to the netsh command if you want it to only last until reboot.)

**Comment by strobilomyces** [comment]
Wow, I have no idea why I never received a notification about this. Serves me right for not logging into Github for a while. Anyhow, thanks for the tip! Updated.
