### ISSUE TITLE
Confusion over script security measures

### ISSUE THREAD

**Issue by ravenise** [strobilomyces/nordvpn-import-ikev2#2]
Your config files are as follows:

[connection]
id=${vpn}.ikev2
uuid=$(uuidgen)
type=vpn
autoconnect=false
permissions=user:$SUDO_USER:;
secondaries=
[vpn]
password-flags=1
user=${username}
encap=yes
address=${vpn}
virtual=yes
**method=eap**
proposal=no
certificate=${certificate}
ipcomp=no
service-type=org.freedesktop.NetworkManager.strongswan
[ipv4]
dns-search=
method=auto
[ipv6]
addr-gen-mode=stable-privacy
dns-search=
ip6-privacy=2
method=auto

on nordvpn's website their configuration file is like this:

conn NordVPN
  keyexchange=ikev2
  dpdaction=clear
  dpddelay=300s
  eap_identity="USERNAME"
  **leftauth=eap-mschapv2**
  left=%defaultroute
  leftsourceip=%config
  right=SERVER
  rightauth=pubkey
  rightsubnet=0.0.0.0/0
  rightid=%any
  type=tunnel
  auto=add 

I see nothing related to eap-mschapv2 in your config files or rightauth=pubkey; 

I see no configuration of IPSEC in your script. Are you using Ipsec/Kiev2, or just Kiev2? What authentication methods are you providing. Does this provide the maximum security provided by Nordvpn? What is going on here?

**Comment by strobilomyces** [comment]
Well, long story short, back in the olden days when I made this, I have a suspicion that I merely copied what NordVPN had at the time. Back then, Network Manager barely functioned with strongSwan.

Anyhow, I'll see what their guide recommends now and update it. Thanks again.

**Comment by strobilomyces** [comment]
Having read NordVPN's latest guide and seeing that they now have an actual Linux app, I don't think this project is useful anymore. I'm going to delete it. Thanks for the input, and sorry again that I didn't see this until today.
